FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt upgrade -y && apt install python3 hostname vim tree iproute2 inetutils-ping arping ncat iptables tcpdump ipset curl openssl dnsutils net-tools charon-systemd -y && \
        rm -rf /var/lib/apt/lists/* && \
        rm -rf /etc/localtime

COPY dist/strongswan-setup /
RUN chmod +x *.sh

# ENTRYPOINT ["/usr/bin/dumb-init", "--"]
