---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - vpn-gw.kube-ovn-operator.com
  resources:
  - ipsecconns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpn-gw.kube-ovn-operator.com
  resources:
  - ipsecconns/finalizers
  verbs:
  - update
- apiGroups:
  - vpn-gw.kube-ovn-operator.com
  resources:
  - ipsecconns/status
  verbs:
  - get
  - patch
  - update
