# permissions for end users to view vpngws.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vpngw-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vpn-gw
    app.kubernetes.io/part-of: vpn-gw
    app.kubernetes.io/managed-by: kustomize
  name: vpngw-viewer-role
rules:
- apiGroups:
  - vpn-gw.kube-ovn-operator.com
  resources:
  - vpngws
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vpn-gw.kube-ovn-operator.com
  resources:
  - vpngws/status
  verbs:
  - get
